import "../styles/globals.css";
import AuthContext from "./context/AuthContext";
import Navbar from "./components/Nav";

export const metadata = {
  title: "ToF Gallery",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthContext>
          <Navbar />
          <main className="relative flex items-center flex-col mx-auto sm:px-16 px-6 min-h-[100vh] bg-gray-200">
            {children}
          </main>
        </AuthContext>
      </body>
    </html>
  );
}
